# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'CWUih1lMjsh4Itzflq5yKg'
  twitter_api_secret: 'xz0HNek2VvvodgBcjxz9mcGewQAUB9GX9fToBRrg'
  
development:
  secret_key_base: 8f183d2699e98e8f50038123bdb217a424110d268d8f369ed6c47a27c5e06b8371dd6a643b514a790687dbd03b414745f1ca7593281fb8c765638bea68c51358
  <<: *default_twitter

test:
  secret_key_base: ed07f5dc675efb225825cebc2bb0d141150713c32ec330515db5962cbbf95f068ac7ff9c520deb4f3035957ec67573a075c6e4fdbabfc2bdedef88af5b8eda5e
  <<: *default_twitter

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  
